name: Deploy On GitHub Action

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    env:
      TITLE: "Seoungmee Park"
      EMAIL: "sw5860@naver.com"
      WORK_TITLE: "SOME TILTLE"
      WORK_DESCRIPTION: "SOME DESCRIPTION"
      
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        
       # Need to fetch reqs if needed
      - name: Installing all necessary packages
        run: pip install -r requirements.txt

      - name: Running the Python script
        run: python main.py
        
      - name: Commit and Push The Results From Python Selenium Action
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "GitHub Actions Results added"
          git push
        with:
          tokens: ${{ secrets.DEPLOY_KEY }}