name: Works auto creation

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Main Workflow Execution
      run: |
        python main_workflow.py
    - name: Commit and Push The Results From Python Selenium Action
      run: |
        git config --local user.name "rukidding0918"
        git config --local user.email "rukidding@khu.ac.kr"
        git add -A
        git commit -m "GitHub Actions Results added"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
